### ISSUE TITLE
The display and sizing of dialogue/comment box when user clicks on the box doesn't match with Scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#100]
The display and sizing of dialogue/comment box when user clicks on the box doesn't match as in Scratch.

![Image](https://github.com/user-attachments/assets/1bc63879-195d-4a57-a0ec-28cda999b8f5)

As per Scratch,

![Image](https://github.com/user-attachments/assets/3e6c9ef8-d4d1-406a-b69c-8d37757c3f55)

**Comment by cwillisf** [comment]
Is it still small if the box isn't empty? If so, I think this one will be important for us.

**Comment by gonfunko** [comment]
Nope, only when empty, size is same/adequate to fit the text comfortably when there's a value. Closing accordingly, thanks!
