### ISSUE TITLE
The dropdown on the block is not displayed on the flyout section

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#102]
The block(backdrop# of stage) is not displayed on the flyout section as it is in the workspace.

![Image](https://github.com/user-attachments/assets/946e7080-6734-440b-9da1-7a33be399fa0)

As per Scratch,

![Image](https://github.com/user-attachments/assets/ebdc91c1-30e7-4981-a715-9c6d46ba0b79)

**Comment by gonfunko** [comment]
This block also reverts to "Stage" if you try to pick a sprite from the second dropdown.

**Comment by plabanTest1** [comment]
Dragging the backdrop block is working as expected. Good to close
![Image](https://github.com/user-attachments/assets/9d5b04f7-843b-4ba6-9d22-d020030df984)
