### ISSUE TITLE
The angle picker is not displayed as per Scratch.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#103]
The angle picker should display an background color in the dropdown, extra padding, and arrow icon.
The functionality should include clicking and dragging the arrow icon to change the angle

![Image](https://github.com/user-attachments/assets/3a6edf9c-ea62-46d0-b436-d3f90e4bf495)

As per Scratch,

![Image](https://github.com/user-attachments/assets/40f503f3-99ac-46b0-bddd-3dbf7c41f2fb)

**Comment by gonfunko** [comment]
Duplicate of #63

**Comment by plabanTest1** [comment]
Working as expected.



![Image](https://github.com/user-attachments/assets/f30979a8-0c8c-4a04-9b7c-1d3477ef8fbc)
