### ISSUE TITLE
The "space" dropdown height limit is not appropriately displayed as per Scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#109]
from the flyout area, drag a block "When space key pressed" to workspace.

![Image](https://github.com/user-attachments/assets/08fe7443-f05d-4969-bf77-bff74f73f380)

As per Scratch,

![Image](https://github.com/user-attachments/assets/110a1eee-e207-49de-9321-9b8f78d512b3)

**Comment by cwillisf** [comment]
I don't think the exact number of items shown is too important, but having the extra space between & around items is probably important for tablets & touchscreens.

**Comment by plabanTest1** [comment]
Working as expected.
![image](https://github.com/user-attachments/assets/3a5cc66b-d2dc-4fa2-b2f1-8a650ac36bb5)
