### ISSUE TITLE
The pencil icon is not displayed in workspace while importing a codeshadow project.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#114]
1. Load the CodeShadow project.
2.  https://scratch.mit.edu/projects/1032119179/editor/
3. Validate the associated blocks displayed on the workspace. 

The drawing pen in the workspace is not getting displayed.

![Image](https://github.com/user-attachments/assets/f6ffdc2c-aec1-4d6e-a004-6c5d9594d49c)

As per Scratch,

![Image](https://github.com/user-attachments/assets/c51935c7-1ecf-4d2e-9c19-8f2ffea3e5a5)

**Comment by gonfunko** [comment]
Scratch proper also doesn't show the sprite icon in the corner of the workspace initially, you have to e.g. select the stage and then switch back for it to show up, which is the same as our behavior. This is arguably buggy, but it's buggy in upstream Scratch so I'm closing this.
