### ISSUE TITLE
Don't allow dragging a block into the define procedure block

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#116]
Currently, it's possible to drag a block into the slot occupied by the being-defined procedure block in the define procedure block. This is silly and should be prevented.
<img width="246" alt="Screenshot 2024-08-08 at 1 51 51 PM" src="https://github.com/user-attachments/assets/79609d69-0762-4b91-8d37-b60f5290b76f">

**Comment by plabanTest1** [comment]
The block is unable to be dragged to a define procedure block. Even after multiple attempts the block is not overlapping on the procedure block. This is as expected.

![Image](https://github.com/user-attachments/assets/81623ef8-dd4c-48be-8d33-5c4bbc380202)
