### ISSUE TITLE
The new variable/list created doesn't get auto checked on the flyout area unlike Scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#135]
When we create a new variable/list, the custom variable/list is automatically checked on the flyout area in Scratch. whereas here this is unchecked.

URL: https://gonfunko.github.io/scratch-gui/index.html

![Image](https://github.com/user-attachments/assets/15961c85-7427-43a5-977d-e1c65b5724de)

![Image](https://github.com/user-attachments/assets/38f415f9-62bf-41e7-90e1-9ac4127905f8)

As per Scratch,

![Image](https://github.com/user-attachments/assets/4ee45e53-5a97-4bea-b7d7-cbcf8b3ff68a)

![Image](https://github.com/user-attachments/assets/537dffb0-094f-4acf-9451-35ab2a5b245c)

**Comment by cwillisf** [comment]
Input from Eric R:

> I agree that we should keep the behavior as is, and display the monitor when you create a variable (which has the side effect of checking the box... not the other way around, right??).
>
> The reasoning in the past was that that people don't necessarily know what a variable is or does, and displaying its value by default helps people discover how it works (and also people don't spontaneously click those check boxes to find out what they do). That said, that's an assumption that was never empirically tested AFAIK. In the absence of evidence either way, I'd say we should keep it as is.
>
> Also it seems likely there are tutorials or curriculum resources out there that depend on this behavior (i.e. they instruct you to create a variable, then update the value and look at the monitor - with no info about the checkbox). e.g. our own clicker game tutorial shows the score monitor.

**Comment by plabanTest1** [comment]
Working as expected.


![Image](https://github.com/user-attachments/assets/72d03f8d-e733-4063-b190-7e00eb6a5396)



![Image](https://github.com/user-attachments/assets/8798fad2-1dbd-4d98-8d18-4d2c136f9f72)
