### ISSUE TITLE
For minimal values there shouldn't be a scrollbar display, especially when right click on a variable

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#136]
![Image](https://github.com/user-attachments/assets/c7b06583-1939-4da7-9448-891133201066)

As per Scratch,

![Image](https://github.com/user-attachments/assets/e7be2298-6a49-43ec-8909-3eda24787071)

**Comment by cwillisf** [comment]
This one won't block us (Scratch Foundation) working on integration with Scratch (maybe obvs?) but will block shipping it to prod

**Comment by plabanTest1** [comment]
Scrollbar is no more displayed, working as expected.



![Image](https://github.com/user-attachments/assets/e25a5f94-19bf-4cc3-801c-833fe6852905)
