### ISSUE TITLE
Investigate if we need to do anything with the backpack - sync with Scratch folks

### ISSUE THREAD

**Issue by BeksOmega** [gonfunko/scratch-blocks#14]

**Comment by cwillisf** [comment]
@gonfunko, want to talk this one through here? I'm happy to meet if that makes sense.

In case it helps, the only backpack thing I can think of that isn't covered by "Share the Love" (dragging code to another sprite) is here:
`scratch-gui/src/lib/backpack/block-to-image.js`

**Comment by gonfunko** [comment]
Is there any way to test the backpack locally? It's disabled/coming soon in scratch-gui when I run it; otherwise I think we can probably safely assume that this is incidentally working now that share the love is too.

**Comment by cwillisf** [comment]
Yes and no... I don't think there's a reasonable way to test the backpack outside of the Scratch team's dev environments (and VPN). If it's reasonably easy for me to try out this version of scratch-blocks, though, I could try it out on my machine and report results. Is it just a matter of `npm ln`?

**Comment by gonfunko** [comment]
Got it! And ~yes, although you'll also need to npm link scratch-blocks to the rc/v12.0.0 branch of Blockly, and that may need a --force.

**Comment by gonfunko** [comment]
Closing this out for now since I expect it works given that we fixed up the relevant events to allow dragging from the workspace to outside of it. If we find this isn't working we can (and should!) reopen.
