### ISSUE TITLE
The total time/response taken for all the contents to be populated on the page is longer than expected.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#142]
1. Open the Developer tools.
2. Run the Lighthouse to fetch performance and accessibility metrics.
3. Load the page.
4. Verify the response time as per metrics

The performance metrics is lower than expected.

![Image](https://github.com/user-attachments/assets/8db913a3-1b08-4f41-8870-4eb77b0109c3)

**Comment by gonfunko** [comment]
This isn't a production page, and outside of not noticeably introducing lag relative to Scratch's behavior we're not aiming for any particular metrics here.
