### ISSUE TITLE
message1 is initially missing from broadcast message picker dropdown

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#149]
The default "message1" broadcast message is shown on the broadcast picker field, but if you click the field to show the menu it's not listed as an option there until a block with that broadcast message is dragged onto the main workspace.

**Comment by plabanTest1** [comment]
The "message1" is displayed along with "New message"

![Image](https://github.com/user-attachments/assets/d044101d-db76-44e1-bd38-29ac56cf16ca)
