### ISSUE TITLE
Category label is offset too far from the top of the flyout when clicking a category in the toolbox

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#151]
When clicking a toolbox category, the flyout scrolls to show that category but with a bit too much space before the category's label in the flyout:

<img width="323" alt="Screenshot 2024-08-29 at 1 46 23 PM" src="https://github.com/user-attachments/assets/c4216a83-3492-4f5f-8fd7-1ad36d2fff75">

**Comment by plabanTest1** [comment]
Working as expected.
![Image](https://github.com/user-attachments/assets/8b7d69cd-fcea-4912-a0a0-0ddd0e4bf998)
