### ISSUE TITLE
Flyout expands to fit the longest block

### ISSUE THREAD

**Issue by GrahamSH-LLK** [gonfunko/scratch-blocks#153]
### Expected Behavior

The flyout should have a fixed width, like in current scratch, and not expand with long blocks.
### Actual Behavior

The flyout width expands with the length of the longest block. Since arbitrary input is allowed in More Blocks, this can allow users to make it impossible to use the workspace for a sprite.
### Steps to Reproduce

Create a very long custom block
![image](https://github.com/user-attachments/assets/1946ac39-8e03-406c-9df0-c3ff5c6d4fe4)

**Comment by plabanTest1** [comment]
Working as expected now.



![Image](https://github.com/user-attachments/assets/c5c1b511-4d40-4d73-b241-33f07bd27d12)
