### ISSUE TITLE
Extension icons misaligned

### ISSUE THREAD

**Issue by GrahamSH-LLK** [gonfunko/scratch-blocks#155]
Extension block icons are aligned differently from vanilla scratch. 
vanilla:
![image](https://github.com/user-attachments/assets/c344801e-3da0-4303-932c-500d943b1d65)
this:
![image](https://github.com/user-attachments/assets/ed38c7c3-3668-4995-a16d-3ae1587dc5b1)

**Comment by plabanTest1** [comment]
As per Spork,
![Image](https://github.com/user-attachments/assets/6d7939c6-81b6-4113-9f75-683c6cd4ec34)

As per Scratch,
![Image](https://github.com/user-attachments/assets/c04aa29b-dfa9-4f8e-9b3b-b0bfb10f2901)
