### ISSUE TITLE
Block drop destination highlights missing on boolean inputs

### ISSUE THREAD

**Issue by GrahamSH-LLK** [gonfunko/scratch-blocks#156]
The block drop destination highlights are missing when dragging anything into a block that accepts a boolean input (eg. `< > and < >`).

vanilla: 
![image](https://github.com/user-attachments/assets/17349475-38aa-4cb9-8b0b-41692189236f)
modern-blockly:
![image](https://github.com/user-attachments/assets/44542d2c-8fef-407c-bccb-f330fe870a12)

**Comment by GrahamSH-LLK** [comment]
Interestingly, it _does_ work if there's already a boolean in the slot.

**Comment by mybearworld** [comment]
The same seems to happen for text/number inputs

**Comment by plabanTest1** [comment]
The block drop destination highlights as expected.

![Image](https://github.com/user-attachments/assets/98ef2467-a126-4fff-866e-db64d66bd868)
