### ISSUE TITLE
Blocks cannot be right-clicked on

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#158]
### Expected Behavior

You can right click on blocks to get various actions.

**Screenshot from Scratch**
![image](https://github.com/user-attachments/assets/f80bb43a-1dfd-481c-a7ad-1b01d1f19470)

### Actual Behavior

You cannot right click on blocks, and instead get an error in the console.

![image](https://github.com/user-attachments/assets/4a49a780-cece-422a-984a-26d1d344e126)

### Steps to Reproduce

- Drag out any block
- Right click on it

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by plabanTest1** [comment]
The right click on the block is working as expected.

![Image](https://github.com/user-attachments/assets/f2eb24e8-3457-4aed-bc18-c6252f4f12f4)
