### ISSUE TITLE
Extension hat blocks have a flat top

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#159]
### Expected Behavior

Extension hat blocks look like other hat blocks.

**Screenshot from Scratch**
![image](https://github.com/user-attachments/assets/c96ab14d-13a3-4ddc-8190-a1371f2f1a1e)

### Actual Behavior

Extension hat blocks have a flat top.

**Screenshot from this fork**
![image](https://github.com/user-attachments/assets/6755184b-4676-4bbc-8102-95f776089c45)

### Steps to Reproduce

- Add an extension with hat blocks like Video Sensing or micro:bit

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by plabanTest1** [comment]
Working as expected.



![Image](https://github.com/user-attachments/assets/3ea53788-3c09-4642-84b4-8995b50ebc40)
