### ISSUE TITLE
Extension names overflow in the category menu

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#160]
### Expected Behavior

Extension names in the category menu wrap around when they're too long.

**Screenshot from Scratch**
![image](https://github.com/user-attachments/assets/b78f1f92-f631-4446-ac4c-be5f7aeadff8)

### Actual Behavior

Extension names in the category menu overflow and go behind the block pane.

**Screenshot from this fork**
![image](https://github.com/user-attachments/assets/f040ad42-4c62-41ab-a020-2084c8104e33)

### Steps to Reproduce

- Add the Video Sensing extension

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by plabanTest1** [comment]
Extension names are displaying as expected.


![Image](https://github.com/user-attachments/assets/574d429d-3e61-4852-a2a9-88149a6d76d0)
