### ISSUE TITLE
Input fields that once had a reporter in them default to "undefined"

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#162]
### Expected Behavior

When an input field used to have a reporter in them, the input fields should still report the text within them.

### Actual Behavior

"undefined" is reported.

### Steps to Reproduce

- Drag out any block with a text/number input field
  ![image](https://github.com/user-attachments/assets/56a4056a-5333-4531-8554-735501ae3adb)
- Put another block in a field
  ![image](https://github.com/user-attachments/assets/a71c97eb-a898-478f-bea0-7e37ceff0b43)
- Drag that block back out
  ![image](https://github.com/user-attachments/assets/693e3055-fe8d-47e1-9feb-d41efeb30b91)
- Change the text within; it still is "undefined"
  ![image](https://github.com/user-attachments/assets/a3c9548b-318c-48be-ae3f-15a2870883a1)

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by plabanTest1** [comment]
Inputs fields are displayed as entered.

![Image](https://github.com/user-attachments/assets/889768d2-6ef2-4693-84dc-8155b23350d8)

![Image](https://github.com/user-attachments/assets/06804cac-bc37-4b36-ab80-8b8ffdb92687)

![Image](https://github.com/user-attachments/assets/6f2ff24f-123a-40f9-9c89-b9075b1f81cd)
