### ISSUE TITLE
Setting high contrast mode when not in a code tab messes up the block colors

### ISSUE THREAD

**Issue by mybearworld** [gonfunko/scratch-blocks#163]
### Expected Behavior

It changes the block colors correctly.

### Actual Behavior

It does this.
![image](https://github.com/user-attachments/assets/9390f540-de64-40b7-b0c4-4c0581f30837)
![image](https://github.com/user-attachments/assets/8ae982ab-5050-415d-9414-3178b2f31af7)

### Steps to Reproduce

- Go to the costumes or sounds tab
- Set the color mode to high contrast

### Operating System and Browser

Windows 11 on MS Edge 128

**Comment by gonfunko** [comment]
Fixed by https://github.com/google/blockly/pull/8572

**Comment by plabanTest1** [comment]
Working as expected now in high contrast mode.

![image](https://github.com/user-attachments/assets/ecb195de-7355-447b-b401-2185e7f57a6d)
