### ISSUE TITLE
Verify package version implications

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#17]
We've bumped the package version to 2.0, but should make sure this won't cause issues elsewhere.

**Comment by cwillisf** [comment]
This seems like a good thing to me :+1:
Since `scratch-blocks` is in the `scratch-*` club, I don't believe a major version bump will cause any problems or even slow anything down.

**Comment by gonfunko** [comment]
Great, thanks! Closing accordingly.
