### ISSUE TITLE
Unable to delete a selected block out of multiple standalone blocks on workspace

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#174]
Drag random blocks onto workspace.
Spread out blocks as standalone not necessarily stacked.
Right click on the block where user can delete it.

Expected: The right click on selected block shows an option of "Delete block". User should be able to delete.

![Image](https://github.com/user-attachments/assets/644ea541-0f54-4933-80a3-435e06825949)

Actual:

![Image](https://github.com/user-attachments/assets/f42e6d98-0fc8-4d77-9eb0-a46f402f76f5)

**Comment by gonfunko** [comment]
This is just the workspace menu as opposed to the block menu, probably due to #158.
