### ISSUE TITLE
The right click seems to be not working on stacks of blocks

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#175]
The right click is not working when clicked on the blocks. anywhere outside within workspace the right click works with options displayed. {**This was working seamlessly earlier, not sure why this is not working now**}

https://screencast.googleplex.com/cast/NjIzNDI5Njc0MTI2NTQwOHxmZmUwMGZkYy03ZA

As per Scratch,

![Image](https://github.com/user-attachments/assets/7671fb36-9ce6-4853-b752-40bf3099933d)

![Image](https://github.com/user-attachments/assets/8900b30c-2173-48ff-96e3-b01c37bf1adf)

**Comment by gonfunko** [comment]
Duplicate of #158.

**Comment by plabanTest1** [comment]
This is now working as expected.
![Image](https://github.com/user-attachments/assets/9e712103-96a6-4008-ae5f-ab2d6ababf70)


![Image](https://github.com/user-attachments/assets/c1b9a8df-f397-437c-a247-f3e46adcaab8)
