### ISSUE TITLE
The colors on a couple of the Sensing blocks is not as per scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#178]
![Image](https://github.com/user-attachments/assets/2045a12a-9b7b-4821-8613-cf7249865539)

As per Scratch,
![Image](https://github.com/user-attachments/assets/cbd061e8-e9d3-4e3c-bd20-cb8fef3d5931)

**Comment by gonfunko** [comment]
This is WAI; the color field's color is generated randomly. If you refresh Scratch itself, the colors will be different every time.
