### ISSUE TITLE
Lengthy comments provided on Comment section defers to that in Scratch

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#185]
Current spork URL.
![Image](https://github.com/user-attachments/assets/41079ec2-3ce4-4e40-a999-ae983caebab1)

Scratch:
![Image](https://github.com/user-attachments/assets/684c17a1-a2cf-4207-ba1f-27e4216425f3)

**Comment by gonfunko** [comment]
It's true that they do diverge here, but I think the comments being scrollable in this case is strictly an improvement.
