### ISSUE TITLE
"define" text is misaligned with baseline of custom block caller block

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#194]
When a custom block definition has a non-label input (number/text/boolean), the "define" text on the custom block definition block is misaligned with the baseline of the sample caller block embedded in the block definition block:

<img width="228" alt="Incorrect baseline in block definition block" src="https://github.com/user-attachments/assets/398f894b-2fce-43ac-8f3f-270ba293801c">

If the custom block only has label inputs however, the baseline is correct/consistent:

<img width="108" alt="Label-only custom block with correct baseline" src="https://github.com/user-attachments/assets/29c00c7e-a96d-4632-9e20-378ae46d486a">

**Comment by plabanTest1** [comment]
The define text is now aligned with custom input blocks. 

![image](https://github.com/user-attachments/assets/d8861e7f-ab8b-4e81-b4d4-d0c9f5e6aa89)
