### ISSUE TITLE
Arguments in sample caller block embedded in custom block definition block are the wrong color

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#195]
When a custom block has arguments, the argument placeholder/shadow blocks shown in the sample caller block embedded in the block definition block are displayed using the same color as the caller block. Instead, they should be the same color as the top-level definition block. Note that when the argument blocks are dragged out, their color is correct. This behavior is the same in both the high contrast and normal themes.

<img width="228" alt="Incorrectly colored argument blocks" src="https://github.com/user-attachments/assets/b0175b1d-436b-4917-8c8a-2d17a4b7a0c8">

**Comment by gonfunko** [comment]
Correct behavior:
<img width="359" alt="Correctly colored argument blocks" src="https://github.com/user-attachments/assets/8cbc8c57-f1e4-43ff-98be-4e18d262c5ae">

**Comment by plabanTest1** [comment]
![image](https://github.com/user-attachments/assets/be3d2d18-91c6-4231-9998-c9b0886c79b5)
