### ISSUE TITLE
There is too much space between blocks and checkboxes in the flyout

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#200]
We have more space between blocks and checkboxes than Scratch does:

<img width="110" alt="Too much padding" src="https://github.com/user-attachments/assets/9ae533ae-d010-4807-9a26-d1184fe5e78f">
<img width="100" alt="Scratch's padding" src="https://github.com/user-attachments/assets/785414a2-eb48-4f96-894b-53f6c1aed505">

**Comment by plabanTest1** [comment]
The spacing between checkbox and block are appropriate as per Scratch
![image](https://github.com/user-attachments/assets/1b6ce407-4fc5-484f-b43f-1f390a2b9b93)
![image](https://github.com/user-attachments/assets/b19ad747-f7b1-4cb9-9ec7-8ee9b8b8990d)
