### ISSUE TITLE
Inter-block spacing is incorrect for hat blocks in the flyout

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#201]
Hat blocks have a bit more spacing between them in the flyout relative to Scratch; in general blocks are spaced the same, and I suspect this may be due to the hat not being taken into account/being positioned negative relative to the block's bounds or something along those lines.

<img width="311" alt="Hat blocks with extra spacing" src="https://github.com/user-attachments/assets/ec246b66-a983-477d-85c8-d785a22272d2">

<img width="313" alt="Hat blocks with normal spacing" src="https://github.com/user-attachments/assets/103ccd6a-8711-4f32-8f55-44d59efe18bc">

**Comment by plabanTest1** [comment]
The spacing between the hat blocks seems to be appropriate.

![image](https://github.com/user-attachments/assets/6d06f987-7a99-4ff8-bbb2-f97149f85f92)
