### ISSUE TITLE
Text/number field should be rounded in the make a block dialog

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#202]
Scratch uses a rounded field for the number/text input, whereas we use a rectangle.
![Screenshot 2024-09-27 at 8 27 08 AM](https://github.com/user-attachments/assets/f32ccdcc-2e2f-4796-88b4-a061a326c1ac)

**Comment by plabanTest1** [comment]
![image](https://github.com/user-attachments/assets/54a42252-fde9-47a4-8a38-848557ff8ffd)
