### ISSUE TITLE
Operator block fields should be empty instead of displaying 0 by default

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#203]
In Scratch, the mathematical operator blocks' fields are empty in the flyout, whereas we display 0 in them.

![image](https://github.com/user-attachments/assets/50a1b251-ca7d-4b6f-89d4-dd42786d9fd5)

**Comment by plabanTest1** [comment]
The operator blocks are displaying as empty instead of 0

![image](https://github.com/user-attachments/assets/1bc47eb3-5969-4ee6-a2ff-807f2774ebe6)
