### ISSUE TITLE
Duplicating an argument reporter block creates a new fount of argument reporter blocks

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#215]
Normally, the argument blocks in a procedure definition block act as sources for copies of that block when dragged. Once a copy is dragged out however, it behaves as a normal block, and dragging it merely moves it, as opposed to spawning a copy. If an argument reporter block is duplicated via the Duplicate contextual menu however, the duplicate will spawn copies when it is dragged.

**Comment by gonfunko** [comment]
This also happens when copying + pasting these blocks.

**Comment by plabanTest1** [comment]
Dragging the duplicate blocks gets dragged around workspace and not create more duplicates.
