### ISSUE TITLE
Preserve Scratch's block duplication functionality

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#25]
In core Blockly, the Duplicate contextual menu just makes a copy of a block offset slightly from the original. In Scratch, the menu attaches the copied block to the cursor as if it were mid-drag, and it follows the cursor until clicked to place it.

**Comment by BeksOmega** [comment]
Got feedback from Eric Rosenbaum that the consensus at Scratch is they prefer the default Blockly behavior. Preserving the scratch behavior would probably end up being super hacky as well. So based on that I'm closing this as not planned.
