### ISSUE TITLE
Customize workspace comment CSS to match Scratch style

### ISSUE THREAD

**Issue by BeksOmega** [gonfunko/scratch-blocks#5]
Dependent on v11 of Blockly core for workspace comment code

**Comment by mmathrani** [comment]
Moving to ready since Blockly V11 Beta will be out today. Please revert to Blocked if need be.

**Comment by BeksOmega** [comment]
The dragging beta is out today, but the workspace comments are still in the works. That should hopefully be done by end of next week! (April 26th)
