### ISSUE TITLE
Blocks are missing shadows during drags

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#59]
While being dragged, Scratch adds drop shadows to blocks:

![Screenshot 2024-05-06 at 10 49 04 AM (2)](https://github.com/gonfunko/scratch-blocks/assets/667459/c1765bd5-0931-4525-af18-b4457fe556b7)

These need to be added.

**Comment by plabanTest1** [comment]
Shadow during drags are displayed
![Image](https://github.com/user-attachments/assets/b2e16dc3-130a-4631-badd-6770fe634e15)
