### ISSUE TITLE
Update Delete Blocks contextual menu item to not reference the number of blocks

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#60]
When right clicking on a stack of blocks, a "Delete N Blocks" menu item is shown, with N corresponding to the number of blocks in the stack. In Scratch proper, this is shown as "Delete Block", regardless of the number of blocks in the stack. The code for handling procedure deletion also looks for the "Delete Block" string literal to patch the implementation to scour the workspace for references to the procedure and warn about them, which is currently broken as a result.

**Comment by BeksOmega** [comment]
If you have a block with a statement input it does count the blocks within the statement input and add it to the context menu text.

**Comment by gonfunko** [comment]
Duplicate of #99
