### ISSUE TITLE
Resolve angle picker skew

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#63]
Our angle picker lacks the background color in the dropdown, extra padding, and arrow icon from Scratch. It also continuously follows the mouse, whereas the Scratch implementation requires clicking and dragging the arrow icon to change the angle.
![Screenshot 2024-05-06 at 2 45 06 PM](https://github.com/gonfunko/scratch-blocks/assets/667459/c4810dd7-847e-46d3-be78-d5eb47d031c1)
![Screenshot 2024-05-06 at 2 45 11 PM](https://github.com/gonfunko/scratch-blocks/assets/667459/3f69f80e-db51-4009-a57d-3f3c756f970f)

**Comment by gonfunko** [comment]
The edge spacing and size of the tick marks also varies.

**Comment by BeksOmega** [comment]
For future ref: I think this is going to require a custom field to fix the tick marks, arrow, and the input interaction.

**Comment by gonfunko** [comment]
> For future ref: I think this is going to require a custom field to fix the tick marks, arrow, and the input interaction.

Yeah, I think this is basically just modernizing the existing core/field_angle.js

**Comment by BeksOmega** [comment]
Also related to https://github.com/gonfunko/scratch-blocks/issues/101

**Comment by cwillisf** [comment]
I can double-check with other folks at Scratch, but my initial take here is:
- the larger arrow bubble is important as a click and touch target, and as a more visually obvious way to say "This is the direction" (as opposed to the line at zero)
- the background color is a "want" but maybe not an absolute "need" (this is the main one I want to double-check)
- everything else is probably NBD
