### ISSUE TITLE
Remove yellow connection indicator

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#64]
Scratch lacks the yellow connection indicator, and only shows the block outline connection indicator.

![Screenshot 2024-05-06 at 2 50 17 PM (2)](https://github.com/gonfunko/scratch-blocks/assets/667459/a64239b1-d097-4275-b02d-adeb3a8e5d42)

**Comment by BeksOmega** [comment]
Relevant docs: https://developers.google.com/blockly/guides/create-custom-blocks/inputs/connection-previews

The built-in one also [respects](https://github.com/google/blockly/blob/171befa7462b4a5288ce0fa775814c267f424e2c/core/insertion_marker_previewer.ts#L63) shouldHighlightConnection which might be enough to fix this.
