### ISSUE TITLE
Align inter-item spacing in the flyout with Scratch

### ISSUE THREAD

**Issue by gonfunko** [gonfunko/scratch-blocks#69]
Item spacing is subtly different:

<table>
<thead>
<tr><th>Scratch</th><th>Us</th></tr>
</thead>
<tbody>
<tr><td><img src="https://github.com/gonfunko/scratch-blocks/assets/667459/9ea4c53b-88a8-4d16-8951-8b8108833ed3"></td><td valign="top"><img src="https://github.com/gonfunko/scratch-blocks/assets/667459/584b1742-828d-44d9-8c5a-c1d7b045c2b8"></td></tr>
</tbody>
</table>

**Comment by plabanTest1** [comment]
Working as expected.

![Image](https://github.com/user-attachments/assets/5df40cf1-dd47-49c1-b5d2-589d10ab1b9e)
