### ISSUE TITLE
Blocks in the flyout area is not appropriately separated.

### ISSUE THREAD

**Issue by plabanTest1** [gonfunko/scratch-blocks#97]
The blocks in the flyout are not separated evenly as per Scratch

![Image](https://github.com/user-attachments/assets/744ead08-62ba-4a22-a530-745d1eb84f65)

**Comment by gonfunko** [comment]
Duplicate of #69

**Comment by plabanTest1** [comment]
Working as expected.



![Image](https://github.com/user-attachments/assets/6d834454-cd52-4c35-96c4-952078923f95)
